name: "main"
on:
  push:
    branches:
      - "master"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Get version"
        id: get-version
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const globber = await glob.create('lipics-v*.cls')
            const files = await globber.glob()
            const class_file = files.at(0)
            const components = class_file.split('/')
            const filename = components.at(-1)
            console.log(components.at(-1))
            console.log(class_file.match(/\/lipics-(v.+)\.cls$/))
            return files
      - name: "Test"
        shell: "bash"
        run: |
          echo '${{ steps.get-version.outputs.result }}'
      - name: "Setup Haskell environment"
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cc-by.pdf
            lipics-logo-bw.pdf
            lipics-v*.cls
            orcid.pdf
  release-full:
    name: "Release (full)"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Setup Haskell environment"
        uses: softprops/action-gh-release@v2
